<?php
/** Client portal: property purchases. */
if ( ! defined( 'ABSPATH' ) ) exit;
OFP_Auth::require_client_login();
$client = OFP_Auth::current_client();
if ( ! OFP_Subscription::has_active( 'listing', $client->id ) ) { wp_safe_redirect( home_url( '/dashboard' ) ); exit; }
global $wpdb; $p=$wpdb->prefix; $message=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['ofp_create_client_purchase'])){
    if(!wp_verify_nonce($_POST['ofp_client_purchase_nonce']??'','ofp_client_create_purchase')){$error='Security check failed. Please try again.';}else{
        $property_id=absint($_POST['property_id']??0); $buyer_source=sanitize_key($_POST['buyer_source']??'offline'); $lead_id=absint($_POST['lead_id']??0); $purchase_type=sanitize_key($_POST['purchase_type']??'installment');
        $buyer_name=sanitize_text_field(wp_unslash($_POST['buyer_name']??'')); $buyer_phone=sanitize_text_field(wp_unslash($_POST['buyer_phone']??'')); $buyer_email=sanitize_email(wp_unslash($_POST['buyer_email']??''));
        $initial=(float)($_POST['initial_payment']??0); $installment_amount=(float)($_POST['installment_amount']??0); $installment_count=absint($_POST['installment_count']??0); $payment_start=sanitize_text_field(wp_unslash($_POST['payment_start_date']??'')); $first_due=sanitize_text_field(wp_unslash($_POST['first_due_date']??'')); $grace=absint($_POST['grace_period_days']??7);
        $property=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}ofp_properties WHERE id=%d AND listing_type='sale' LIMIT 1",$property_id));
        if(!$property)$error='Please choose one of your sale properties.'; elseif((int)$property->client_id!==(int)$client->id)$error='You can only create purchases for your own properties.'; elseif(!$buyer_name||!$buyer_phone)$error='Buyer name and phone are required.'; elseif($buyer_email&&!is_email($buyer_email))$error='Buyer email is invalid.';
        if(!$error&&$buyer_source==='lead'){
            $lead=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$p}ofp_leads WHERE id=%d AND client_id=%d LIMIT 1",$lead_id,(int)$client->id));
            if(!$lead)$error='The selected lead was not found in your account.'; else { if(!$buyer_name)$buyer_name=$lead->name; if(!$buyer_phone)$buyer_phone=$lead->phone; if(!$buyer_email)$buyer_email=$lead->email; if($lead->property_id&&(int)$lead->property_id!==$property_id)$error='The selected lead belongs to a different property.'; }
        }
        if(!$error){$purchase_id=OFP_Property_Purchase_Service::create(['property_id'=>$property_id,'purchase_type'=>$purchase_type,'lead_id'=>$buyer_source==='lead'?$lead_id:null,'buyer_name'=>$buyer_name,'buyer_phone'=>$buyer_phone,'buyer_email'=>$buyer_email,'initial_payment'=>$initial,'installment_amount'=>$installment_amount,'installment_count'=>$installment_count,'payment_start_date'=>$payment_start,'first_due_date'=>$first_due,'grace_period_days'=>$grace]); if(is_wp_error($purchase_id))$error=$purchase_id->get_error_message(); else $message='Purchase #'.(int)$purchase_id.' created successfully.';}
    }
}
$my_properties=$wpdb->get_results($wpdb->prepare("SELECT id,title,price FROM {$p}ofp_properties WHERE client_id=%d AND listing_type='sale' AND status IN ('live','pending_upload') ORDER BY title ASC",(int)$client->id));
$my_leads=$wpdb->get_results($wpdb->prepare("SELECT id,name,phone,email,property_id FROM {$p}ofp_leads WHERE client_id=%d ORDER BY created_at DESC LIMIT 300",(int)$client->id));
$my_purchases=$wpdb->get_results($wpdb->prepare("SELECT pu.*,p.title AS property_title FROM {$p}ofp_property_purchases pu LEFT JOIN {$p}ofp_properties p ON p.id=pu.property_id WHERE pu.client_id=%d ORDER BY pu.created_at DESC LIMIT 100",(int)$client->id));
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Property Purchases — OFast Pipeline</title><?php wp_head(); ?><link rel="stylesheet" href="<?php echo esc_url(OFP_URL.'assets/css/client-portal.css'); ?>"></head><body class="ofp-portal-body"><?php include OFP_PATH.'public/templates/partials/nav.php'; ?><div class="ofp-container"><div style="padding-bottom:60px;"><h1 style="font-size:22px;font-weight:700;margin:0 0 24px;">Property Purchases</h1><?php if($error): ?><div class="ofp-alert ofp-alert-error"><?php echo esc_html($error); ?></div><?php endif; ?><?php if($message): ?><div class="ofp-alert ofp-alert-success"><?php echo esc_html($message); ?></div><?php endif; ?>
<div class="ofp-card" style="margin-bottom:24px;"><h3>Create Purchase</h3><p class="ofp-hint">Record an outright sale or create an installment purchase. No buyer account is created.</p><form method="post"><?php wp_nonce_field('ofp_client_create_purchase','ofp_client_purchase_nonce'); ?><input type="hidden" name="ofp_create_client_purchase" value="1"><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;">
<div><label>Property</label><select name="property_id" required style="width:100%;"><option value="">Select sale property</option><?php foreach($my_properties as $property): ?><option value="<?php echo esc_attr($property->id); ?>"><?php echo esc_html($property->title.' — NGN '.number_format((float)$property->price,2)); ?></option><?php endforeach; ?></select></div>
<div><label>Purchase Type</label><select name="purchase_type" id="ofp-purchase-type" style="width:100%;"><option value="installment">Installment</option><option value="outright">Outright / Full Payment</option></select></div>
<div><label>Buyer Source</label><select name="buyer_source" id="ofp-buyer-source" style="width:100%;"><option value="offline">Offline Buyer</option><option value="lead">Existing Lead</option></select></div>
<div id="ofp-lead-wrap" style="display:none;"><label>Existing Lead</label><select name="lead_id" id="ofp-lead-id" style="width:100%;"><option value="">Select lead</option><?php foreach($my_leads as $lead): ?><option value="<?php echo esc_attr($lead->id); ?>"><?php echo esc_html(($lead->name?:'Unnamed lead').' — '.$lead->phone); ?></option><?php endforeach; ?></select></div>
<div><label>Buyer Name</label><input type="text" name="buyer_name" required style="width:100%;"></div><div><label>Buyer Phone</label><input type="text" name="buyer_phone" required style="width:100%;"></div><div><label>Buyer Email</label><input type="email" name="buyer_email" style="width:100%;"></div>
<div class="installment-field"><label>Initial Payment</label><input type="number" step="0.01" min="0" name="initial_payment" style="width:100%;"></div><div class="installment-field"><label>Installment Amount</label><input type="number" step="0.01" min="0" name="installment_amount" style="width:100%;"></div><div class="installment-field"><label>Number of Installments</label><input type="number" min="1" name="installment_count" style="width:100%;"></div><div class="installment-field"><label>Payment Starts</label><input type="date" name="payment_start_date" style="width:100%;"></div><div class="installment-field"><label>First Due Date</label><input type="date" name="first_due_date" style="width:100%;"></div><div class="installment-field"><label>Grace Period (days)</label><input type="number" min="0" max="365" value="7" name="grace_period_days" style="width:100%;"></div>
</div><p><button class="button button-primary" type="submit">Create Purchase</button></p></form></div>
<div class="ofp-card"><h3>Recent Purchases</h3><div style="overflow-x:auto;"><table class="widefat striped" style="min-width:1150px;"><thead><tr><th>ID</th><th>Buyer</th><th>Property</th><th>Type</th><th>Total</th><th>Paid</th><th>Balance</th><th>First Due</th><th>Status</th></tr></thead><tbody><?php if(empty($my_purchases)): ?><tr><td colspan="9">No purchases yet.</td></tr><?php else: foreach($my_purchases as $purchase): ?><tr><td>#<?php echo esc_html($purchase->id); ?></td><td><strong><?php echo esc_html($purchase->buyer_name); ?></strong><br><small><?php echo esc_html($purchase->buyer_phone); ?></small></td><td><?php echo esc_html($purchase->property_title?:'—'); ?></td><td><?php echo esc_html(ucfirst($purchase->purchase_type?:'installment')); ?></td><td>NGN <?php echo esc_html(number_format((float)$purchase->total_price,2)); ?></td><td>NGN <?php echo esc_html(number_format((float)$purchase->amount_paid,2)); ?></td><td><strong>NGN <?php echo esc_html(number_format((float)$purchase->balance,2)); ?></strong></td><td><?php echo $purchase->first_due_date?esc_html(wp_date('M j, Y',strtotime($purchase->first_due_date))):'—'; ?></td><td><?php echo esc_html(ucfirst($purchase->status)); ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></div>
<script>(function(){var t=document.getElementById('ofp-purchase-type'),fields=document.querySelectorAll('.installment-field'),s=document.getElementById('ofp-buyer-source'),w=document.getElementById('ofp-lead-wrap'),l=document.getElementById('ofp-lead-id');function sync(){fields.forEach(function(f){f.style.display=t.value==='outright'?'none':'';f.querySelector('input')?.removeAttribute('required');});}function leadSync(){w.style.display=s.value==='lead'?'':'none';l.disabled=s.value!=='lead';if(s.value!=='lead')l.value='';}t.addEventListener('change',sync);s.addEventListener('change',leadSync);sync();leadSync();})();</script><?php wp_footer(); ?></body></html>
